// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBke5FBi9DzGmaoyWYXirDNZtg_LeFc76Q',
    appId: '1:606607786193:android:4495a7c9adc023ebda85f0',
    messagingSenderId: '606607786193',
    projectId: 'task-manager-56e7e',
    databaseURL: 'https://task-manager-56e7e-default-rtdb.firebaseio.com',
    storageBucket: 'task-manager-56e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpnCKg8aASfPyP6wK9sAYfPmadZkAKmUg',
    appId: '1:606607786193:ios:91057f75d97e622fda85f0',
    messagingSenderId: '606607786193',
    projectId: 'task-manager-56e7e',
    databaseURL: 'https://task-manager-56e7e-default-rtdb.firebaseio.com',
    storageBucket: 'task-manager-56e7e.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
}
